[build]
base = "python:3.11-bookworm"
dependencies = [
    "opencv-python-headless", 
    "numpy", 
    "torch", 
    "torchvision", 
    "requests", 
    "pandas", 
    "seaborn", 
    "tqdm", 
    "psutil",
    "ultralytics"
]
system_packages = [] # 이제 프레임워크가 자동으로 의존성을 해결합니다.

[runtime]
gpu = false  # Prototype runs on CPU as per user code
